### ISSUE TITLE
Social buttons on the top right of each page have different interactions on hover.

### ISSUE THREAD

**Issue by bpdesigns** [slco-2016/q1_report_long#3]
Tumblr button does not change color on hover but the twitter button does. It would be ideal to make that consistent. My suggestion would be to add a slight color state change on the tumblr button, but I'm also fine with removing the color state change on the twitter button.

**Comment by kuanb** [comment]
Will look into... Styling is automatically created by Twitter and tumble respectively

**Comment by bpdesigns** [comment]
Not a big deal. Alternative would be to make them text links like the presentation report.
